export const enum Constants {
    //CRYPTO MARKET
    SEARCH_SYMBOL = 'SEARCH_SYMBOL',
    //Call Api
    FETCH_REQUEST = 'FETCH_REQUEST',
    FETCH_SUCCESS = 'FETCH_SUCCESS',
    FETCH_ERROR='FETCH_ERROR'    
}